// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6v90uvdNxq9_9vTx01bvBx9HP00u1zGI',
    appId: '1:1018068995472:web:5db43ca5f07aa58c09b715',
    messagingSenderId: '1018068995472',
    projectId: 'flutter-a0cf6',
    authDomain: 'flutter-a0cf6.firebaseapp.com',
    storageBucket: 'flutter-a0cf6.firebasestorage.app',
    measurementId: 'G-Z3DM3J6HRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTWkwuF8ngeXuICmhqpYuQh0VVQSN-ZW0',
    appId: '1:1018068995472:android:bb980a8b9bc098d109b715',
    messagingSenderId: '1018068995472',
    projectId: 'flutter-a0cf6',
    storageBucket: 'flutter-a0cf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUFFhSeNhyR1eMSSWrVXfouqNUUg2oPvY',
    appId: '1:1018068995472:ios:9726bdf6fb86fac909b715',
    messagingSenderId: '1018068995472',
    projectId: 'flutter-a0cf6',
    storageBucket: 'flutter-a0cf6.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUFFhSeNhyR1eMSSWrVXfouqNUUg2oPvY',
    appId: '1:1018068995472:ios:9726bdf6fb86fac909b715',
    messagingSenderId: '1018068995472',
    projectId: 'flutter-a0cf6',
    storageBucket: 'flutter-a0cf6.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6v90uvdNxq9_9vTx01bvBx9HP00u1zGI',
    appId: '1:1018068995472:web:8066cbad796ff3f309b715',
    messagingSenderId: '1018068995472',
    projectId: 'flutter-a0cf6',
    authDomain: 'flutter-a0cf6.firebaseapp.com',
    storageBucket: 'flutter-a0cf6.firebasestorage.app',
    measurementId: 'G-YQLGJXCTC4',
  );
}
